config/routes.rb
Tracker2::Application.routes.draw do

  get "form2/form"

  resources :tasks

  resources :proyects

  resources :users

end

app/models/country.rb
class Country < ActiveRecord::Base
	  has_many :users
end

app/models/language.rb
class Language < ActiveRecord::Base
	  has_many :users
end

app/models/proyect.rb
class Proyect < ActiveRecord::Base
	  belongs_to :proyect_status
	  belongs_to :user
	  has_many :tasks
end

app/models/proyect_status.rb
class ProyectStatus < ActiveRecord::Base
	has_many :proyects
end

app/models/task.rb
class Task < ActiveRecord::Base
	  belongs_to :user
	  belongs_to :proyect
	  belongs_to :task_type
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
	  belongs_to :country
	  belongs_to :language
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/form2_controller.rb
class Form2Controller < ApplicationController
  
  # GET /form2/1/form
  def form
	  @task = Task.new
	  @task.proyect_id = params[:id]

  end


end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyects }
    end
  end

  def form2
  
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
    @proyect = Proyect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/new
  # GET /proyects/new.json
  def new
    @proyect = Proyect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/1/edit
  def edit
    @proyect = Proyect.find(params[:id])
  end



  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(params[:proyect])

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render json: @proyect, status: :created, location: @proyect }
      else
        format.html { render action: "new" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyects/1
  # PUT /proyects/1.json
  def update
    @proyect = Proyect.find(params[:id])

    respond_to do |format|
      if @proyect.update_attributes(params[:proyect])
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect = Proyect.find(params[:id])
    @proyect.destroy

    respond_to do |format|
      format.html { redirect_to proyects_url }
      format.json { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form2_helper.rb
module Form2Helper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/form2/form.html.haml
- model_class = @task.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")

= form_for @task, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :titulo, :class => 'control-label'
    .controls
      = f.text_field :titulo, :class => 'text_field'
  .control-group
    = f.label :descripcion, :class => 'control-label'
    .controls
      = f.text_area :descripcion, :class => 'text_area'
  .control-group
    = f.label :fecha_inicio, :class => 'control-label'
    .controls
      = f.date_select :fecha_inicio, :class => 'date_select'
  .control-group
    = f.label :fecha_finalizacion, :class => 'control-label'
    .controls
      = f.date_select :fecha_finalizacion, :class => 'date_select'
  .control-group
    = f.label :dificultad, :class => 'control-label'
    .controls
      = f.number_field :dificultad, :class => 'number_field'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .control-group
    = f.label :proyect_id, :class => 'control-label'
    .controls
      = f.number_field :proyect_id, :disabled => true,:hint => "an example of disabled input"
  .control-group
    = f.label :task_type_id, :class => 'control-label'
    .controls
      = f.number_field :task_type_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker2</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Tracker2"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Tracker2
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Link 1", "/path1"
                %li= link_to "Link 2", "/path2"
                %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"


app/views/proyects/_form.html.haml
= form_for @proyect, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :titulo, :class => 'control-label'
    .controls
      = f.text_field :titulo, :class => 'text_field'
  .control-group
    = f.label :descripcion, :class => 'control-label'
    .controls
      = f.text_area :descripcion, :class => 'text_area'
  .control-group
    = f.label :fecha_inicio, :class => 'control-label'
    .controls
      = f.date_select :fecha_inicio, :class => 'date_select'
  .control-group
    = f.label :fecha_finalizacion, :class => 'control-label'
    .controls
      = f.date_select :fecha_finalizacion, :class => 'date_select'
  .control-group
    = f.label :proyect_status_id, :class => 'control-label'
    .controls
      = collection_select :proyect, :proyect_status_id, ProyectStatus.all, :id, :estado
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = collection_select :proyect, :user_id, User.all, :id, :name
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), proyects_path, :class => 'btn'

app/views/proyects/edit.html.haml
- model_class = @proyect.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/proyects/hola.html.haml
%h1 Editing proyect
= render 'form'
= link_to 'Show', @proyect
|
\#{link_to 'Back', proyects_path}

app/views/proyects/index.html.haml
- model_class = Proyect.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:titulo)
      %th= model_class.human_attribute_name(:descripcion)
      %th= model_class.human_attribute_name(:fecha_inicio)
      %th= model_class.human_attribute_name(:fecha_finalizacion)
      %th= model_class.human_attribute_name(:proyect_status_id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @proyects.each do |proyect|
      %tr
        %td= link_to proyect.id, proyect_path(proyect)
        %td= proyect.titulo
        %td= proyect.descripcion
        %td= proyect.fecha_inicio
        %td= proyect.fecha_finalizacion
        %td= ProyectStatus.find(proyect.proyect_status_id).estado
        %td= User.find(proyect.user_id).name
        %td=l proyect.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_proyect_path(proyect), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), proyect_path(proyect), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
          = link_to t('.show', :default => t("helpers.links.show")), proyect, :class => 'btn btn-mini'          
= link_to t('.new', :default => t("helpers.links.new")), new_proyect_path, :class => 'btn btn-primary'

app/views/proyects/new.html.haml
- model_class = @proyect.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/proyects/show.html.haml
- model_class = @proyect.class
%h1=t '.title', :default => model_class.model_name.human



%p
  %strong= model_class.human_attribute_name(:titulo) + ':'
  %br
  = @proyect.titulo
%p
  %strong= model_class.human_attribute_name(:descripcion) + ':'
  %br
  = @proyect.descripcion
%p
  %strong= model_class.human_attribute_name(:fecha_inicio) + ':'
  %br
  = @proyect.fecha_inicio
%p
  %strong= model_class.human_attribute_name(:fecha_finalizacion) + ':'
  %br
  = @proyect.fecha_finalizacion
%p
  %strong= model_class.human_attribute_name(:proyect_status_id) + ':'
  %br
  = ProyectStatus.find(@proyect.proyect_status_id).estado
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = User.find(@proyect.user_id).name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), proyects_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_proyect_path(@proyect), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), proyect_path(@proyect), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'
%br/

%h1=t 'tasks'
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:titulo)
      %th= model_class.human_attribute_name(:descripcion)
      %th= model_class.human_attribute_name(:fecha_inicio)
      %th= model_class.human_attribute_name(:fecha_finalizacion)
      %th= model_class.human_attribute_name(:dificultad)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:proyect_id)
      %th= model_class.human_attribute_name(:task_type_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - Proyect.find(@proyect.id).tasks.each do |task|
      %tr
        %td= link_to task.id, task_path(task)
        %td= task.titulo
        %td= task.descripcion
        %td= task.fecha_inicio
        %td= task.fecha_finalizacion
        %td= task.dificultad
        %td= User.find(task.user_id).name
        %td= task.proyect_id
        %td= TaskType.find(task.task_type_id).tipo
        %td=l task.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.Nueva_Tarea'), :controller => "form2", :action => "form", :id => @proyect, :class => 'btn btn-mini'
%br/
%br/

app/views/tasks/_form.html.haml
= form_for @task, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :titulo, :class => 'control-label'
    .controls
      = f.text_field :titulo, :class => 'text_field'
  .control-group
    = f.label :descripcion, :class => 'control-label'
    .controls
      = f.text_area :descripcion, :class => 'text_area'
  .control-group
    = f.label :fecha_inicio, :class => 'control-label'
    .controls
      = f.date_select :fecha_inicio, :class => 'date_select'
  .control-group
    = f.label :fecha_finalizacion, :class => 'control-label'
    .controls
      = f.date_select :fecha_finalizacion, :class => 'date_select'
  .control-group
    = f.label :dificultad, :class => 'control-label'
    .controls
      = f.number_field :dificultad, :class => 'number_field'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .control-group
    = f.label :proyect_id, :class => 'control-label'
    .controls
      = f.number_field :proyect_id, :class => 'number_field'
  .control-group
    = f.label :task_type_id, :class => 'control-label'
    .controls
      = f.number_field :task_type_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn'

app/views/tasks/edit.html.haml
- model_class = @task.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/tasks/index.html.haml
- model_class = Task.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:titulo)
      %th= model_class.human_attribute_name(:descripcion)
      %th= model_class.human_attribute_name(:fecha_inicio)
      %th= model_class.human_attribute_name(:fecha_finalizacion)
      %th= model_class.human_attribute_name(:dificultad)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:proyect_id)
      %th= model_class.human_attribute_name(:task_type_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to task.id, task_path(task)
        %td= task.titulo
        %td= task.descripcion
        %td= task.fecha_inicio
        %td= task.fecha_finalizacion
        %td= task.dificultad
        %td= User.find(task.user_id).name
        %td= task.proyect_id
        %td= TaskType.find(task.task_type_id).tipo 
        %td=l task.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
          = link_to t('.show', :default => t("helpers.links.show")), task, :class => 'btn btn-mini' 
= link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary'

app/views/tasks/new.html.haml
- model_class = @task.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/tasks/show.html.haml
- model_class = @task.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:titulo) + ':'
  %br
  = @task.titulo
%p
  %strong= model_class.human_attribute_name(:descripcion) + ':'
  %br
  = @task.descripcion
%p
  %strong= model_class.human_attribute_name(:fecha_inicio) + ':'
  %br
  = @task.fecha_inicio
%p
  %strong= model_class.human_attribute_name(:fecha_finalizacion) + ':'
  %br
  = @task.fecha_finalizacion
%p
  %strong= model_class.human_attribute_name(:dificultad) + ':'
  %br
  = @task.dificultad
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = User.find(@task.user_id).name
%p
  %strong= model_class.human_attribute_name(:proyect_id) + ':'
  %br
  = @task.proyect_id
%p
  %strong= model_class.human_attribute_name(:task_type_id) + ':'
  %br
  = TaskType.find(@task.task_type_id).tipo

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(@task), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(@task), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'text_field'
  .control-group
    = f.label :mail, :class => 'control-label'
    .controls
      = f.text_field :mail, :class => 'text_field'
  .control-group
    = f.label :username, :class => 'control-label'
    .controls
      = f.text_field :username, :class => 'text_field'
  .control-group
    = f.label :biografia, :class => 'control-label'
    .controls
      = f.text_area :biografia, :class => 'text_area'
  .control-group
    = f.label :country_id, :class => 'control-label'
    .controls
      = f.number_field :country_id, :class => 'number_field'
  .control-group
    = f.label :language_id, :class => 'control-label'
    .controls
      = f.number_field :language_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = @user.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped 
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:password)
      %th= model_class.human_attribute_name(:mail)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:biografia)
      %th= model_class.human_attribute_name(:country_id)
      %th= model_class.human_attribute_name(:language_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.name
        %td= user.password
        %td= user.mail
        %td= user.username
        %td= user.biografia
        %td= Country.find(user.country_id).country
        %td= Language.find(user.language_id ).language
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
          = link_to t('.show', :default => t("helpers.links.show")), user, :class => 'btn btn-mini'           

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = @user.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/show.html.haml
- model_class = @user.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:password) + ':'
  %br
  = @user.password
%p
  %strong= model_class.human_attribute_name(:mail) + ':'
  %br
  = @user.mail
%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:biografia) + ':'
  %br
  = @user.biografia
%p
  %strong= model_class.human_attribute_name(:country_id) + ':'
  %br
  = Country.find(@user.country_id).country
%p
  %strong= model_class.human_attribute_name(:language_id) + ':'
  %br
  = Language.find(@user.language_id).language

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'